#!/usr/bin/env bash

echo "-------------------------------------------------"
echo RUNNING COMMAND scm_item_add
echo "-------------------------------------------------"
echo ""

. $(dirname "$BASH_SOURCE")/scripts/scm_item_add.sh
