#!/usr/bin/env bash

echo "-------------------------------------------------"
echo RUNNING COMMAND scm_item_checkout
echo "-------------------------------------------------"
echo ""



. $(dirname "$BASH_SOURCE")/scripts/scm_item_checkout.sh
