#!/usr/bin/env bash

echo "-------------------------------------------------"
echo RUNNING COMMAND scm_changelist_shelve
echo "-------------------------------------------------"
echo ""

. $(dirname "$BASH_SOURCE")/scripts/scm_changelist_shelve.sh

